version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/mongodb

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    volumes:
      - etcd-data:/etcd-data
    command:
      - etcd
      - --name
      - myetcdnode
      - --data-dir
      - /etcd-data
      - --advertise-client-urls
      - http://0.0.0.0:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
      target: crawler
    ports:
      - "50051:50051"
    environment:
      - HOST_IP=${HOST_IP}
      - PORT=50051
    depends_on:
      - etcd

volumes:
  mongodb_data:
  etcd-data:
  redis_data:
