version: '3.8'

x-common:
  &common
  environment:
    &common-env
    MONGODB_CONN: mongodb://admin:password@mongodb:27017
    ETCD_CONN: http://etcd:2379
    MYSQL_CONN: 'mysql+pymysql://admin:passwird@mysql/mydatabase'


services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      <<: *common-env
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    container_name: etcd
    command:
      - etcd
      - --name
      - myetcdnode
      - --data-dir
      - /etcd_data
      - --advertise-client-urls
      - http://0.0.0.0:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"
    volumes:
      - etcd_data:/etcd_data

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: admin
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER: crawler
    environment:
        <<: *common-env
        SERVER: crawler
    container_name: crawler
    depends_on:
      - mongodb
    volumes:
      - ./config.yaml:/app/config.yaml

  eventserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER: eventserver
    environment:
      <<: *common-env
      SERVER: eventserver
    container_name: eventserver
    depends_on:
      - etcd
      - mongodb
    volumes:
      - ./config.yaml:/app/config.yaml

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER: webserver
    environment:
        <<: *common-env
        SERVER: webserver
    ports:
      - "8080:8080"
    container_name: webserver
    depends_on:
      - eventserver
    volumes:
      - ./config.yaml:/app/config.yaml

volumes:
  mongodb_data:
  etcd_data:
  redis_data:
  mysql_data:
