version: '3.8'

x-common:
  &common
  environment:
    &common-env
    MONGODB_CONN: mongodb://admin:password@mongodb:27017
    ETCD_CONN: http://etcd:2379

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      <<: *common-env
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  etcd:
    image: quay.io/coreos/etcd:v3.5.0
    volumes:
      - etcd_data:/etcd_data
    command:
      - etcd
      - --name
      - myetcdnode
      - --data-dir
      - /etcd_data
      - --advertise-client-urls
      - http://0.0.0.0:2379
      - --listen-client-urls
      - http://0.0.0.0:2379
    ports:
      - "2379:2379"
      - "2380:2380"

  crawler:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER: crawler
    environment:
        <<: *common-env
        SERVER: crawler
    container_name: webcrawler
    volumes:
      - ./config.yaml:/app/config.yaml

  eventserver:
#    network_mode: "host"
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER: eventserver
    environment:
      <<: *common-env
      SERVER: eventserver
    container_name: eventserver
    depends_on:
      - etcd
    volumes:
      - ./config.yaml:/app/config.yaml

  webserver:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        SERVER: webserver
    environment:
        <<: *common-env
        SERVER: webserver
    ports:
      - "8080:8080"
    container_name: webserver
    depends_on:
      - eventserver
    volumes:
      - ./config.yaml:/app/config.yaml

volumes:
  mongodb_data:
  etcd_data:
  redis_data:


